name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: nipmo-wesbites    # correct name from publish profile
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: npm install and build
      run: |
        echo "Verifying package.json exists:"
        test -f package.json || { echo "Error: package.json not found"; exit 1; }
        echo "Installing dependencies..."
        npm ci --legacy-peer-deps
        echo "Building application..."
        npm run build
      env:
        CI: true

    - name: Prepare for deployment
      run: |
        echo "Preparing deployment package..."
        # Create a production-ready package.json
        node -e 'const pkg=JSON.parse(require("fs").readFileSync("package.json")); const newPkg={...pkg, scripts:{"start":"next start"}}; require("fs").writeFileSync("package.json", JSON.stringify(newPkg, null, 2));'
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        startup-command: 'npm start'  # Next.js production startup command